---
# ###################################################################
# Example : VSP One GAD consistency group Playbook
# ###################################################################
- name: VSP One GAD consistency group Module
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

    secondary_connection_info:
      address: "{{ secondary_storage_address }}"
      username: "{{ vault_secondary_storage_username }}"
      password: "{{ vault_secondary_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Suspend GAD pairs using consistency group Ids
    ####################################################################
    - name: Suspend GAD pairs using consistency group Ids
      hitachivantara.vspone_block.vsp.hv_vsp_one_gad_consistency_group:
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
        state: "suspended"
        spec:
          consistency_group_ids: [0, 1]
          continue_io_volume: "PRIMARY"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Resync GAD pairs using consistency group Ids
    ####################################################################
    - name: Resync GAD pairs using consistency group Ids
      hitachivantara.vspone_block.vsp.hv_vsp_one_gad_consistency_group:
        connection_info: "{{ connection_info }}"
        secondary_connection_info: "{{ secondary_connection_info }}"
        state: "resynced"
        spec:
          consistency_group_ids: [0, 1]
          copy_pace: 10
          io_preference_mode: "KEEP_CURRENT_SETTING"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
