---
namespace: hitachivantara
name: vspone_block
version: 4.2.1
readme: README.md
authors:
  - Hitachi Vantara Ansible Team
description: >
  Ansible modules to manage Hitachi Storage systems using the Hitachi VSP One platform.
  These modules provide a simplified and automated way to configure and manage Hitachi storage systems,
  enabling seamless integration with Ansible playbooks and workflows.
license:
  - GPL-3.0-or-later
tags:
  - hitachi
  - hv
  - hitachi_vantara
  - sds_block
  - vsp
  - vsp_one
  - storage
  - pegasus
dependencies: {}
repository: https://github.com/hitachi-vantara/vspone-block-ansible
documentation: https://docs.ansible.com/ansible/devel/collections/hitachivantara/vspone_block/
issues: https://github.com/hitachi-vantara/vspone-block-ansible/issues
build_ignore:
  - tests/integration/ # Example: Ignore integration tests
  - .git
  - collection_build.sh
  - .pylintrc
  - .gitignore
  - Dockerfile
  - pylint_run_report.txt
  - .rabi
  - plugins/module_utils/unit_test
  - scripts
  - .vscode
  - spec
  - version.txt
  - lambda_package
  - run_linter.py
  - lint_report.txt
  - sanity_test_report.txt
  - file_name_wo_ext_cwd.sh
  - test_ansible_doc.sh
