# version include file.
#
# This file is autogenerated.
# BUILD is a placeholder. It is updated during the build process.
#
ANSIBLE_RELEASE_MAJOR=2
ANSIBLE_RELEASE_MINOR=3
ANSIBLE_RELEASE_PATCH=0
ANSIBLE_RELEASE_BUILD=007
ANSIBLE_VERSION="02.3.0.7"
