---
####################################################################
# Example : Cluster Network Facts Playbook
####################################################################
- name: Cluster Network Facts Playbook
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
  ####################################################################
  # Task Name : Get Cluster Network Information
  ####################################################################
    - name: Get Cluster Network Information
      hitachivantara.vspone_block.sds_block.hv_sds_block_storage_network_setting_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
