---
####################################################################
# Example : User Facts Playbook
####################################################################
- name: User Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
  ####################################################################
  # Task Name : Get all users Domains
  ####################################################################
    - name: Get all users
      hitachivantara.vspone_block.sds_block.hv_sds_block_user_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    ####################################################################
    # Task Name : Get one user by id
    ####################################################################
    - name: Get one user by id
      hitachivantara.vspone_block.sds_block.hv_sds_block_user_facts:
        connection_info: "{{ connection_info }}"
        spec:
          id: "admin"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
