---
####################################################################
# Example : SDSB Cluster Configuration Facts Playbook
####################################################################
- name: SDSB Cluster Configuration Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    ####################################################################
    # Task Name : Get cluster configuration information
    # Note: This task is supported for Bare Metal and Google Cloud.
    #       This task is not supported for AWS and Microsoft Azure.
    ####################################################################
    - name: Get cluster configuration information
      hitachivantara.vspone_block.sds_block.hv_sds_block_cluster_config_facts:
        connection_info: "{{ connection_info }}"

      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
