---
####################################################################
# Example : SDSB Software Update File Facts Playbook
####################################################################
- name: SDSB Software Update File Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
  ####################################################################
  # Task Name : Get software update file information
  ####################################################################
    - name: Get software update file information
      hitachivantara.vspone_block.sds_block.hv_sds_block_software_update_file_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
