---
####################################################################
# Example : Storage Pool Facts Playbook
####################################################################
- name: Storage Pool Facts
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml

  vars:
    # Common connection info for all tasks
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"

  tasks:
    #########################################################################
    # Task Name : Get all storage pools
    #########################################################################
    - name: Get all storage pools
      hitachivantara.vspone_block.sds_block.hv_sds_block_storage_pool_facts:
        connection_info: "{{ connection_info }}"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #########################################################################
    # Task Name : Get storage pool by Names
    #########################################################################
    - name: Get storage pool by Names
      hitachivantara.vspone_block.sds_block.hv_sds_block_storage_pool_facts:
        connection_info: "{{ connection_info }}"
        spec:
          names: ["SP01", "SP02"]
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result

    #########################################################################
    # Task Name : Get storage pool by ID
    #########################################################################
    - name: Get storage pool by ID
      hitachivantara.vspone_block.sds_block.hv_sds_block_storage_pool_facts:
        connection_info: "{{ connection_info }}"
        spec:
          id: "a632b0d8-0ae6-408c-ad41-555cdde9fe83"
      register: result

    - name: Debug the result variable
      ansible.builtin.debug:
        var: result
