---
# ######################################################################
# Default variables for hv_vsp_primary_secondary_journal_creation role
# These can be overridden in playbooks or inventory
# ######################################################################

hv_vsp_primary_secondary_journal_creation_connection_info: {}
hv_vsp_primary_secondary_journal_creation_secondary_connection_info: {}
# hv_vsp_primary_secondary_journal_creation_number_of_journals: null
# hv_vsp_primary_secondary_journal_creation_primary_journal_ids: []
# hv_vsp_primary_secondary_journal_creation_secondary_journal_ids: []
# hv_vsp_primary_secondary_journal_creation_primary_pool_id: ""
# hv_vsp_primary_secondary_journal_creation_secondary_pool_id: ""
# hv_vsp_primary_secondary_journal_creation_primary_parity_group_id: null
# hv_vsp_primary_secondary_journal_creation_secondary_parity_group_id: null
hv_vsp_primary_secondary_journal_creation_size_in_gb: 8
