kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_ethernetswitches_crd.yaml
kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_fcswitches_crd.yaml
kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_hostgroups_crd.yaml
kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_infrastructuresparepools_crd.yaml
kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_luns_crd.yaml
kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_servers_crd.yaml
kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_storagesystems_crd.yaml
kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_ucpsystems_crd.yaml
kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_vlans_crd.yaml
kubectl apply -f ../../deploy/crds/ucp.hitachivantara.com_zones_crd.yaml
